name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  upload_file:
    name: Upload File to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install boto3 python-dotenv

      - name: Set Environment Variables
        run: echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

      - name: Run Upload Script
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: python ./app/upload_to_s3.py
